Add button to display full list in About page
Chocobozzz/PeerTube pull request #2688
Opened 2020-04-27 10:29 UTC by MahdiTurki

#2397 

Instead of scrolling down to get more followers/followings, the user can press show full list that will display the full list. The button will disappear when pressed and the full list is displayed.
I haven't managed to display the number of followers/followings.

2020-04-27 10:36 UTC, DontUseGithub commented
> The button will disappear when pressed and the full list is displayed.

I think the user would expect that button to go to the bottom of that list and have a reversed action and name ("hide full list").

2020-04-27 10:46 UTC, rigelk commented on client/src/app/+about/about-follows/about-follows.component.html
> +    <a id="showMore" href="javascript:;" *ngIf="!showMoreFollowings" (click)="loadAllFollowings()" (click)= "showMoreFollowings=true">Show full list</a>
why do you use `href="javascript:;"`?

2020-04-27 10:49 UTC, rigelk commented on client/src/app/+about/about-follows/about-follows.component.html
> +    <a id="showMore" href="javascript:;" *ngIf="!showMoreFollowings" (click)="loadAllFollowings()" (click)= "showMoreFollowings=true">Show full list</a>
please use a class instead of an id ; they benefit from the component encapsulation so ids are not as useful.

2020-04-27 10:50 UTC, rigelk commented on client/src/app/+about/about-follows/about-follows.component.scss
> +  color: black;
please use something more generic, like the `peertube-button-link` mixin.

2020-04-27 10:50 UTC, rigelk commented on client/src/app/+about/about-follows/about-follows.component.ts
> +    while(hasMoreItems(this.followingsPagination)) {
```suggestion
    while (hasMoreItems(this.followingsPagination)) {
```

2020-04-27 10:50 UTC, rigelk commented on client/src/app/+about/about-follows/about-follows.component.ts
> +    while(hasMoreItems(this.followersPagination)) {
```suggestion
    while (hasMoreItems(this.followersPagination)) {
```

2020-04-27 10:51 UTC, rigelk commented on client/src/app/+about/about-follows/about-follows.component.ts
> +      this.loadMoreFollowers();
```suggestion
      this.loadMoreFollowers()
```

2020-04-27 10:51 UTC, rigelk commented on client/src/app/+about/about-follows/about-follows.component.ts
> +  showMoreFollowings = false;
```suggestion
  showMoreFollowers = false
  showMoreFollowings = false
```

2020-04-27 10:53 UTC, rigelk commented on client/src/app/+about/about-follows/about-follows.component.html
> +    <a id="showMore" href="javascript:;" *ngIf="!showMoreFollowings" (click)="loadAllFollowings()" (click)= "showMoreFollowings=true">Show full list</a>
please use the `i18n` attribute.

2020-04-27 10:53 UTC, rigelk commented on client/src/app/+about/about-follows/about-follows.component.html
> +    <a id="showMore" href="javascript:;" *ngIf="!showMoreFollowings" (click)="loadAllFollowings()" (click)= "showMoreFollowings=true">Show full list</a>
please remove trailing spaces.

2020-04-27 10:54 UTC, rigelk commented on client/src/app/+about/about-follows/about-follows.component.html
> +
please remove trailing spaces.

2020-04-27 13:00 UTC, MahdiTurki commented
> > The button will disappear when pressed and the full list is displayed.
> 
> I think the user would expect that button to go to the bottom of that list and have a reversed action and name ("hide full list").

I think it won't matter that much. Why would he want to hide the full list if he chose to display it?

2020-04-27 14:40 UTC, DontUseGithub commented
> 
> I think it won't matter that much. Why would he want to hide the full list if he chose to display it?

Various reasons, maybe he has clicked it by mistake or perhaps he wanted to search for a specific name (via ctrl+F) and then hide one list and open the second one. 

But it just feels right to have a way of reverting back whatever you've done, I even remember reading about this somewhere, it's how good designs are made.

> Make actions reversible – be forgiving
> 
> This rule means that the user should always be able to quickly backtrack whatever they are doing. This allows users to explore the product without the constant fear of failure — when a user knows that errors can be easily undone, this encourages exploration of unfamiliar options. On the contrary, if a user has to be extremely careful with every action they take, it leads to a slower exploration and nerve-racking experience that no one wants.

https://xd.adobe.com/ideas/process/ui-design/4-golden-rules-ui-design/

2020-04-27 14:46 UTC, MahdiTurki commented
You are totally right. I will keep that in mind in the future.
I will think of a way on how to hide the list and will try to implement it.

2020-04-27 15:09 UTC, DontUseGithub commented
>  I will think of a way on how to hide the list and will try to implement it.

I hope you meant not to hide it totally, just revert it back to how it was before the user has clicked that button :)

2020-04-27 15:12 UTC, MahdiTurki commented
> I hope you meant not to hide the entire list, just revert it back to how it was before the user has clicked that button :)

My bad! Yes that's what I meant.

2020-04-27 20:12 UTC, MahdiTurki commented
Now the user has the option to show the full list, and when it's pressed, the user can scroll down, hide the full list and will only see the first 20 followers/followings.

2020-07-08 19:00 UTC, test2a commented
a quick question here. how about we display server stats along with the video stored size on the server? i mean there are servers on the stats page with thousands of videos. If we had a way of knowing the cpu size or the ram of that server, one could understand the transcoding their server has to do, the people it has to serve and other stuff

2020-12-03 07:32 UTC, kontrollanten commented
@rigelk Is there anything more that needs to be done on this (except solving the file conflict)?

2020-12-03 12:39 UTC, rigelk requested changes
@kontrollanten yes, showing the count of instances. The UI for empty lists has not been worked on either (buttons should not appear), and actions should match the color scheme for links.

![](https://user-images.githubusercontent.com/6329880/101019078-b6876a00-356c-11eb-8c25-ab3c46feadbe.png)

2020-12-03 14:25 UTC, kontrollanten commented
@MahdiTurki Thanks for your contribution! Do you think that you can do the last fixes requested by @rigelk ? It would be nice to be able to merge this :)

2020-12-03 16:38 UTC, MahdiTurki commented
Hi, sure thing. I will start working on them soon.
> and actions should match the color scheme for links. 


@rigelk, I don't get what you mean exactly, could you please elaborate more?

2020-12-03 21:23 UTC, rigelk commented
@MahdiTurki just have links use the main color :wink:

2020-12-04 05:30 UTC, kontrollanten commented
> @MahdiTurki just have links use the main color

Is it the Show more/less links that you're thinking of? I guess we should add the `button-grey` mixin and remove the `padding: 0`;

![image](https://user-images.githubusercontent.com/6680299/101125520-bc775c80-35f9-11eb-95aa-056a54345ad3.png)

2020-12-04 09:23 UTC, rigelk commented
Either is fine

2020-12-12 21:45 UTC, MahdiTurki commented
I managed to display the count of instances. I tested with 2 different instances and it worked fine.
I also managed to hide the show/hide button when there are no followers or followings.

2020-12-14 09:26 UTC, Chocobozzz commented
Merged manually. Thanks @MahdiTurki

2020-12-14 09:26 UTC, closed without merging