Set canonical link to original video/playlist url
Chocobozzz/PeerTube pull request #3406
Opened 2020-12-06 18:24 UTC by tcitworld

The local URL was used instead of the original url

## Description

The local URL was used instead of the original url

## Related issues

Previously fixed in https://github.com/Chocobozzz/PeerTube/issues/1539

Added a test to check but didn't manage to run them, so they're all yours.

2020-12-06 20:23 UTC, kontrollanten requested changes

2020-12-06 20:23 UTC, kontrollanten commented on server/tests/client.ts
> +    servers = await flushAndRunMultipleServers(2)
A fancy way would be `[server, secondServer] = await flushAndRunMultipleServers(2)`

2020-12-06 20:23 UTC, kontrollanten commented on server/tests/client.ts
> +      const res = await uploadVideo(servers[0].url, servers[0].accessToken, { name: 'video' })
Do we really need to upload a video here? According to line 78 there's already a video on the server.

If we need this line, then line 78 has to be updated (that's why tests are failing).

2020-12-06 20:23 UTC, kontrollanten commented on server/tests/client.ts
> +      expect(res.text).to.contain(`<link rel="canonical" href="${videoOriginalUrl}" />`)
By using `server.video` we could change the test to:

```
      const res = await makeHTMLRequest(servers[1].url, '/videos/watch/' + server.video.uuid)
      expect(res.text).to.contain(`<link rel="canonical" href="${server.video.url}" />`)
```

2020-12-08 10:15 UTC, Chocobozzz commented
Thanks @tcitworld  @kontrollanten

2020-12-08 10:15 UTC, merged