add ability to remove one's avatar for account and channels
Chocobozzz/PeerTube pull request #3467
Opened 2020-12-14 20:12 UTC by rigelk

## Description

This PR adds a delete route for account avatars and one for channel avatars.

TODO:

- [ ] also cover `user-edit`

## Has this been tested?

- [x] 💭 no, because this PR is a draft and still needs work

## Screenshots

No avatar:
![Screenshot_2020-12-14 Account settings - PeerTube(1)](https://user-images.githubusercontent.com/6329880/102129532-c7c75500-3e4f-11eb-982a-23b6ac31e5cd.png)
With an avatar:
![Screenshot_2020-12-14 Account settings - PeerTube](https://user-images.githubusercontent.com/6329880/102129541-cc8c0900-3e4f-11eb-8ee2-71734b69745c.png)

2020-12-15 05:27 UTC, kontrollanten approved these changes

2021-01-04 17:58 UTC, kimsible approved these changes

2021-01-11 10:45 UTC, Chocobozzz requested changes

2021-01-11 10:45 UTC, Chocobozzz commented on client/src/app/shared/shared-main/account/actor-avatar-info.component.scss
> +::ng-deep .popover-avatar-info .popover-body {
Please scope `::ng-deep` using a parent select (for example: `.actor-img-edit-container ::ng-deep ...`)

2021-01-11 10:45 UTC, Chocobozzz commented on client/src/app/shared/shared-main/account/actor-avatar-info.component.ts
> +    return Actor.GET_ACTOR_AVATAR_URL(this.actor)
Please don't use a getter that returns the result of a function, it's a bad practice and could lead to detector change issues.

2021-01-13 08:12 UTC, merged