client: add iOS icon
Chocobozzz/PeerTube pull request #3538
Opened 2021-01-02 21:08 UTC by kontrollanten

## Description
iOS wants it's own markup to display custom icons on the home screen.

## Related issues
Closes #2939

## Has this been tested?
No, I couldn't find any way to test it other than create an own release and deploy it to some server. I hope this is okay anyway since the risks are low.

- [x] 🙅 no, because they aren't needed

2021-01-04 06:43 UTC, test2a commented
![Screenshot_20210104-090726_1](https://user-images.githubusercontent.com/39449563/103507566-83930780-4e85-11eb-9803-3e9f3d5f1cba.png)
i just checked peertube3.cpy.re, peervideo.ru on my android 8 running firefox and using the "install" feature. the icons have the orange background mixing with the middle triangle of the logo... can this be fixed?

2021-01-04 07:17 UTC, kontrollanten commented
I'd say that configuring the background color is a separate issue. Strange though that the background color in the manifest (https://peertube3.cpy.re/manifest.webmanifest) is set to white.

2021-01-04 09:21 UTC, Chocobozzz requested changes

2021-01-04 09:21 UTC, Chocobozzz commented on client/src/index.html
> +    <link rel="apple-touch-icon" href="/client/assets/images/icons/144x144.png" sizes="144x144" />
These paths do not work

2021-01-04 09:21 UTC, Chocobozzz commented
Please use release/3.0.0 as target branch :)

2021-01-05 09:48 UTC, Chocobozzz commented
Thanks @kontrollanten

2021-01-05 09:48 UTC, merged