Allow users/visitors to search through an account's videos
Chocobozzz/PeerTube pull request #3589
Opened 2021-01-12 14:33 UTC by rigelk

## Description

Adds a search icon that on click reveals a search input. Upon validating the search (pressing enter), a listing of videos is taken and filtered with the search terms.

## Related issues

related to meta #3486

## Has this been tested?

- [ ] 👍 yes, I added tests to the test suite
- [x] 💭 no, because this PR is a draft and still needs work
- [ ] 🙅 no, because they aren't needed

## Screenshots

![Screenshot_2021-01-12 Search videos within account - PeerTube](https://user-images.githubusercontent.com/6329880/104327069-b0c96080-54ea-11eb-827d-4b3bfb1780ed.png)

2021-01-13 08:04 UTC, Chocobozzz requested changes

2021-01-13 08:04 UTC, Chocobozzz commented on client/src/app/+accounts/account-search/account-search.component.ts
> +  set search (value: string) {
Use a function `updateSearch (search: string)`

2021-01-13 14:12 UTC, rigelk commented
@Chocobozzz where should I place tests? I can’t find any existing tests for the accounts API (juste their validators).

2021-01-18 09:07 UTC, Chocobozzz commented
Please rebase from develop when the develop tests will be fixed.

2021-01-19 12:43 UTC, merged