add channel and playlist stats to server stats endpoint
Chocobozzz/PeerTube pull request #3747
Opened 2021-02-17 11:08 UTC by rigelk

## Description

Adds the number of local playlists, local channels and active local channels on various timeframes (akin to active users stats): daily/weekly/monthly.

## Has this been tested?

- [x] 👍 yes, I added tests to the test suite, though they might not be enough

2021-02-18 10:07 UTC, Chocobozzz requested changes

2021-02-18 10:07 UTC, Chocobozzz commented on server/models/video/video-channel.ts
> +      const query = {
Please make a raw sql request instead

2021-02-18 10:07 UTC, Chocobozzz commented on server/models/video/video-playlist.ts
> +    const totalLocalPlaylists = await VideoPlaylistModel.scope({
Don't use this scope, just make a regular request on public local playlists

2021-02-18 10:07 UTC, Chocobozzz commented on server/tests/api/server/stats.ts
> +      expect(data.totalLocalDailyActiveVideoChannels).to.equal(1)
Only count that active channels === 1 is not enough: create another channel and check it's taken into account after an upload and not before

Also please correctly test `totalLocalPlaylists`

2021-02-26 11:24 UTC, rigelk commented
@Chocobozzz still missing the `totalLocalPlaylists` tests but otherwise ready for re-review

2021-03-02 09:23 UTC, Chocobozzz submitted a review, later dismissed

2021-03-02 09:23 UTC, Chocobozzz commented on server/models/video/video-channel.ts
> +AND             ("Videos"."createdAt" > Now() - interval '${days}d')
`publishedAt`

2021-03-02 09:23 UTC, Chocobozzz commented on server/tests/api/server/stats.ts
> +      const videoChannel = server.videoChannel = resChannel.body.videoChannels.find(v => v.name === videoChannelProperties.name)
Please don't override `server.videoChannel`. Just use a global variable instead. Also, you can use the answer of `addVideoChannel` to get the channel id: https://github.com/Chocobozzz/PeerTube/blob/develop/server/tests/api/search/search-activitypub-videos.ts#L104

This should resolve the test api-2 failure

2021-04-12 07:37 UTC, Chocobozzz commented
Please fix tests

2021-04-12 09:19 UTC, merged