client: hide publish button when publish is disabled
Chocobozzz/PeerTube pull request #3808
Opened 2021-03-02 18:18 UTC by kontrollanten

## Description
Hides publish button, top right corner, when uploads are disabled.

## Related issues
Closes #3807 

## Has this been tested?

- [x] 👍 yes, light tests as follows are enough

1) Set video quota for new users to unlimited.
1) Logout.
1) See the upload button.

1) Set video quota for new users to 0.
1) Logout.
1) Don't see the upload button.

1) Set the video quota for new users to 0.
1) Set the video quota for a particular user to unlimited.
1) Login as that user.
1) See the publish button.

## Screenshots

![image](https://user-images.githubusercontent.com/6680299/109695312-08e81f00-7b8c-11eb-9dc2-044498f64f9f.png)

2021-03-03 14:39 UTC, rigelk requested changes

2021-03-03 14:39 UTC, rigelk commented on client/src/app/header/header.component.ts
> +  @Input() showPublishButton: boolean
```suggestion
  @Input() showPublishButton = true
```

2021-03-03 14:39 UTC, rigelk commented on client/src/app/app.component.ts
> +    }
```suggestion
    return this.authService.isLoggedIn()
      ? this.authService.getUser().videoQuota !== 0
      : this.serverConfig.user.videoQuota !== 0
```

2021-03-09 00:27 UTC, kimsible commented
Hmm hiding the publish is now in the user scenario @rigelk ?

https://github.com/Chocobozzz/PeerTube/pull/3357#issuecomment-733666215

2021-03-09 05:48 UTC, rigelk commented
The user is logged in and doesn't have any quota, that's not the same situation.

2021-03-22 08:23 UTC, kontrollanten commented
What's the status of this? Is there anything I can do?

2021-03-22 09:13 UTC, Chocobozzz commented
Sorry for the late review/answer @kontrollanten

Hiding the upload button has already been discussed in https://github.com/Chocobozzz/PeerTube/pull/3357 so it's not a feature we want to implement.

What I can do is to add a `userInformationLoaded` plugin hook, and a `getServerConfig` helper on the client so admins can create/install a plugin that hides this upload button depending on their need.

2021-03-22 09:47 UTC, closed without merging

2021-03-22 20:46 UTC, kimsible commented
> Sorry for the late review/answer @kontrollanten
> 
> Hiding the upload button has already been discussed in #3357 so it's not a feature we would like to implement.
> 
> What I can do is to add a `userInformationLoaded` plugin hook, and a `getServerConfig` helper on the client so admins can create/install a plugin that hides this upload button depending on their need.

Thanks @Chocobozzz, sounds a very good compromise.

>> In my opinion the real problem is that publish button is confusing with the search box at left, we may click on the publish button to run a search.

> This is exactly the problem we're facing. But that's a separate issue then I guess.

Yep @kontrollanten it has been reported by some of our members too. If it can help we tried to hack it with a simple CSS override but you'll have a problem with the main container search and the auto-complete will not follow. So yes, in my opinion, the only way to resolve properly this issue (or center the search box ? many things could actually be proposed) is to edit the template angular source file.

2021-03-24 10:42 UTC, Chocobozzz commented
> This is exactly the problem we're facing. But that's a separate issue then I guess.

A UX work on the header is planned

> What I can do is to add a userInformationLoaded plugin hook, and a getServerConfig helper on the client so admins can create/install a plugin that hides this upload button depending on their need.

Done in https://github.com/Chocobozzz/PeerTube/commit/7bc572c7531580600d02b4fc5f1b6cf54df139f0