Resume videos for non-logged in users
Chocobozzz/PeerTube pull request #3885
Opened 2021-03-24 06:10 UTC by kontrollanten

## Description
Stores the current video duration in local storage for non-logged in users so that they can go back to a video and continue where they ended.

Upon app init a check is done to cleanup old durations.

## Related issues
closes #3866

## Has this been tested?

- [x] 👍 yes, light tests as follows are enough

## Resume
1) Logout.
1) Watch a video for a few seconds.
1) Reload the page.

## Cleanup
1) Edit the local storage and change the date in `peertube-videojs-video-watch` to a date more than 31 days back.
1) Reload the page.
1) See that the duration has been cleared.

2021-03-24 12:44 UTC, kontrollanten commented on client/src/app/app.component.ts
> +    setTimeout(cleanupVideoWatch, 5)
```suggestion
    setTimeout(cleanupVideoWatch, 1500) // Run in timeout to ensure we're not blocking the UI
```

2021-03-30 07:09 UTC, Chocobozzz requested changes

2021-03-30 07:09 UTC, Chocobozzz commented on client/src/assets/player/peertube-player-local-storage.ts
> +    console.error(error)
"Cannot parse video watch history from local storage"

2021-03-30 07:09 UTC, Chocobozzz commented on client/src/assets/player/peertube-player-local-storage.ts
> +  setLocalStorage('video-watch', JSON.stringify(newData))
`video-watch-history`

2021-03-30 07:09 UTC, Chocobozzz commented on client/src/assets/player/peertube-player-local-storage.ts
> +  return setLocalStorage(`video-watch`, JSON.stringify({
`video-watch-history`

2021-03-30 07:09 UTC, Chocobozzz commented on client/src/app/app.component.ts
> +    setTimeout(cleanupVideoWatch, 1500) // Run in timeout to ensure we're not blocking the UI
Move this in video-watch component to not import player stuff in the main component

2021-03-30 07:09 UTC, Chocobozzz commented on client/src/assets/player/peertube-player-local-storage.ts
> +      date: `${now.getFullYear()}-${now.getUTCMonth() + 1}-${now.getUTCDate()}`
Why don't you use `.toISOString()`?

2021-03-30 07:09 UTC, Chocobozzz commented on client/src/assets/player/peertube-plugin.ts
>            .catch(err => console.error('Cannot notify user is watching.', err))
Please indent this catch

2021-03-31 09:26 UTC, Chocobozzz commented
Thanks

2021-03-31 09:26 UTC, merged