Minimal PeertubeModalService to open settings from "can be redefined..."
Chocobozzz/PeerTube pull request #3923
Opened 2021-04-05 00:52 UTC by aschaap

## Description

Fixes #2576.

## Related issues

## Has this been tested?

- [ ] 👍 yes, I added tests to the test suite
- [ ] 👍 yes, light tests as follows are enough
- [ ] 💭 no, because this PR is a draft and still needs work
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

In the dev environment, open the About page and click on "can be redefined by the users". The expected result is that the settings dialog opens.

2021-04-05 07:42 UTC, Chocobozzz requested changes

2021-04-05 07:42 UTC, Chocobozzz commented on client/src/app/menu/menu.component.ts
> +      .subscribe((msg) => this.openQuickSettings())
`() => this.openQuickSettings`

2021-04-05 07:42 UTC, Chocobozzz commented on client/src/app/shared/shared-instance/instance-features-table.component.ts
> +    ) { }
Align `) { }` with `constructor`

2021-04-05 07:42 UTC, Chocobozzz commented on client/src/app/shared/shared-main/peertube-modal/peertube-modal.service.ts
> +  openQuickSettingsSubject = new Subject<any[]>()
Should be `new Subject<void>()`

2021-04-05 12:59 UTC, aschaap commented on client/src/app/menu/menu.component.ts
> +      .subscribe((msg) => this.openQuickSettings())
Thank you for your prompt review!

2021-04-05 13:34 UTC, aschaap commented
Failing api-2 test:
1) Should have a valid playlist oEmbed response

Failing api-3 tests:
1) Should have the correct thumbnails
1) Should automatically update the thumbnail when adding an element
1) Should create a playlist on server 2 and have the playlist on server 1 but not on server 3

@Chocobozzz, I'm not confident these failing tests are related to the changes you suggested; perhaps there is an issue somewhere in the testing infrastructure?

2021-04-06 06:57 UTC, Chocobozzz commented
Thanks for the PR and sorry for the tests, my bad.

2021-04-06 06:57 UTC, merged