Reducing tag input excessive padding; fixes #3915
Chocobozzz/PeerTube pull request #3927
Opened 2021-04-06 16:07 UTC by aschaap

## Description

Removed the use of `!important` that caused this issue, and specified rules more in line with `theme.default.css` to minimize overrides and unnecessary rules to ensure tag input fields do not have excessive padding. Ensured entered tags have a 3px margin on the left to maintain their positioning.

## Related issues

Fixes #3915.

## Has this been tested?
- [X] 🙅 no, because they aren't needed

Visually inspected the following relevant input fields in Firefox and a Chrome-based browser (screenshots below, in order listed):
- Advanced search tag inputs
- Video (metadata) editing tag input
- Transcoding configuration inputs (for which 149e4cc, which contained the CSS rule with `!important` seemed to be intended)

## Screenshots
![advanced-search-tags](https://user-images.githubusercontent.com/8865084/113741927-197e3e80-96d0-11eb-965d-da6972765338.png)
![video-tags](https://user-images.githubusercontent.com/8865084/113741928-197e3e80-96d0-11eb-89b2-fd0ccd7ded90.png)
![transcoding_config_inputs](https://user-images.githubusercontent.com/8865084/113741926-197e3e80-96d0-11eb-840d-305103f05777.png)

2021-04-06 20:28 UTC, rigelk requested changes
hi @aschaap and thanks for the PR! LGTM but please compress your CSS selectors.

2021-04-06 20:28 UTC, rigelk commented on client/src/sass/ng-select.scss
> +  }
```suggestion
  &.ng-select-multiple .ng-select-container .ng-value-container {
    padding-left: 12px;
    .ng-value {
      margin-left: 3px;
    }
  }
```

2021-04-06 21:48 UTC, aschaap commented
Hi @rigelk , happy to help. I compressed the selectors as you requested.

2021-04-06 23:21 UTC, rigelk approved these changes

2021-04-07 06:39 UTC, merged

2021-04-07 06:39 UTC, Chocobozzz commented
Thanks @rigelk @aschaap