Added a "previous" button on player when watching playlist
Chocobozzz/PeerTube pull request #3982
Opened 2021-04-18 08:46 UTC by Poslovitch

## Description

I have added a "previous" button on the player, as requested in https://github.com/Chocobozzz/PeerTube/issues/3485. 

There are currently a few issues though:
* It duplicates code from `findNextPlaylistVideo()` and `navigateToPreviousPlaylistVideo()`
* Light tests showed this button was showing even when the user was not watching a playlist 

## Related issues

Resolves https://github.com/Chocobozzz/PeerTube/issues/3485

## Has this been tested?

- [ ] 👍 yes, I added tests to the test suite
- [ ] 👍 yes, light tests as follows are enough
- [x] 💭 no, because this PR is a draft and still needs work
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Screenshots

![image](https://user-images.githubusercontent.com/20014332/115139614-289baf80-a033-11eb-8f8c-060579cbcc2b.png)

2021-04-19 08:04 UTC, Chocobozzz requested changes

2021-04-19 08:04 UTC, Chocobozzz commented on client/src/app/+videos/+video-watch/video-watch.component.ts
> +        previousVideo: () => this.zone.run(() => {
Assign this property in a dedicated `if` below `const option = {` so you don't display it when it's not a playlist

2021-04-25 12:37 UTC, Poslovitch commented
Okay, now, what about the code duplication?

2021-04-26 08:53 UTC, Chocobozzz commented
I refactored in https://github.com/Chocobozzz/PeerTube/pull/3982/commits/c32a3f7d5fdadeec1259ac8cf2788fd74b925cb2

Thanks for the PR @Poslovitch

2021-04-26 08:54 UTC, merged