Expose to plugin a way to reset categories to their initial state
Chocobozzz/PeerTube pull request #4214
Opened 2021-06-29 17:47 UTC by lutangar

## Description

Expose a `resetCategories` method on the `PluginCategoriesManager` allowing a plugin developer to reset *customizations* done on the `VIDEO_CATEGORIES` to be clean on demand.

> - add a `resetConstants` method allowing to clean only one `type` of *alteration* for a specific plugin.
> - make `hash` map global for easier reference and dry up constants methods a little bit

This would help simplify some customization workflow when it involves renaming, updating, deleting, etc...

> I hesitated to create another method `getCategories` on the manager because I'm having another other issue where I find myself unable to call the API to retrieve the list of the categories. In the `register` method when the instance restarted the Rest API is not yet available... but I'll probably create a separate issue. 
> Would *reading* infos about the constants from these managers be considered insane? Shall it always go through the Rest API instead?

### Possible evolutions (or further refacto)

- expose such method on other *ConstantsManger*
- move `VideoConstant` interface to shared and rename \
- create a `PluginConstantManager` interface such as:
```
export interface PluginConstantManager {
  add: (key: string, label: string) => boolean
  delete: (key: string) => boolean
  reset: () => void
}
```
> All *managers* could then be created generically and reduce code duplication

## Related issues

> see https://framacolibri.org/t/plugin-system-issues/12417 for some background

## Has this been tested?

- [x] 👍 yes, I added tests to the test suite
- [ ] 💭 no, because this PR is a draft and still needs work
- [ ] 🙅 no, because this PR does not update server code
- [ ] 🙋 no, because I need help <!-- Detail how we can help you >

2021-06-30 09:51 UTC, Chocobozzz requested changes
Thanks!

2021-06-30 09:51 UTC, Chocobozzz commented on server/tests/plugins/video-constants.ts
> +
Add

```
    expect(categories[42]).to.exist
    expect(categories[43]).to.exist
```

2021-06-30 09:51 UTC, Chocobozzz commented on server/lib/plugins/register-helpers.ts
> +const hash: { [key in AlterableVideoConstant]: VideoConstant } = {
`constantsHash`

2021-06-30 10:20 UTC, lutangar commented
Thanks for the review!

...but I still wonder:

> Would *reading* infos about the constants from these managers be considered insane? Shall it always go through the Rest API instead?

Also what's your sentiment on these suggestions?

> - expose such method on other *ConstantsManger*
> - move `VideoConstant` interface to shared and rename the client interface which has the same name
> - create a `PluginConstantManager` interface

More details in previous comment :arrow_up:

2021-06-30 14:26 UTC, Chocobozzz commented
> Would reading infos about the constants from these managers be considered insane?

No it's definitely the way to do. Altering the object like we do is not very clean. I would just use instead:

```ts
export interface ConstantManager <K> {
  add: (key: k, label: string) => boolean
  delete: (key: k) => boolean
  get: () => { [ id: K ]: string }
  reset: () => void
}
```

2021-07-21 13:46 UTC, Chocobozzz commented
Closing in favour of https://github.com/Chocobozzz/PeerTube/pull/4251

2021-07-21 13:46 UTC, closed without merging