Display avatar in video miniatures
Chocobozzz/PeerTube pull request #4823
Opened 2022-02-28 23:55 UTC by kontrollanten

## Description
Display avatars in video miniatures

## Related issues
closes #4560

## Has this been tested?

- [x] 🙅 no, because this PR does not update server code

## Screenshots
![image](https://user-images.githubusercontent.com/6680299/156078699-7fcaf642-512a-4c66-969d-8d62a12ed53e.png)

2022-03-01 07:33 UTC, Chocobozzz commented
Please use an opt-in config for now: https://github.com/Chocobozzz/PeerTube/blob/develop/config/default.yaml#L624

(thanks for the videos list fix, I put it in develop and added a test in https://github.com/Chocobozzz/PeerTube/commit/242f52253e46ce0ffd7349cb06bcd887bb89cf06)

2022-03-03 20:46 UTC, kontrollanten commented
Fixed @Chocobozzz It was pretty hard find a nice way to set component input default value from the config. The other option I found was to set the value in every places that my-videos-list is used, but that wouldn't be totally nice either.

2022-03-04 09:32 UTC, Chocobozzz requested changes

2022-03-04 09:32 UTC, Chocobozzz commented on config/default.yaml
> +      display_avatar: false
`display_author_avatar` for consistency

2022-03-04 09:57 UTC, Chocobozzz requested changes

2022-03-04 09:57 UTC, Chocobozzz commented on server/initializers/config.ts
> +        get DISPLAY_AVATAR () { return config.get<boolean>('client.videos.miniature.display_author_avatar') }
`DISPLAY_AUTHOR_AVATAR`

2022-03-04 09:57 UTC, Chocobozzz commented on server/lib/server-config-manager.ts
> +            displayAvatar: CONFIG.CLIENT.VIDEOS.MINIATURE.DISPLAY_AVATAR,
`displayAuthorAvatar`

2022-03-04 09:57 UTC, Chocobozzz commented on shared/models/server/server-config.model.ts
> +        displayAvatar: boolean
`displayAuthorAvatar`

2022-03-04 09:57 UTC, Chocobozzz commented on client/src/app/shared/shared-video-miniature/videos-list.component.ts
> +        avatar: this.serverService.getHTMLConfig().client.videos.miniature.displayAvatar,
`displayAuthorAvatar`

2022-03-08 12:39 UTC, merged