Expose PeerTube socket to plugins
Chocobozzz/PeerTube pull request #5239
Opened 2022-09-07 00:11 UTC by kontrollanten

## Description
Expose socket to plugins, so that they can send notifications and update live video state.

## Related issues
#3282

## Has this been tested?
Doesn't make sense to test this.

2022-09-27 05:10 UTC, AnvarKhatik commented
Can I Contribute This Project & Can You Help Me To Guide

2022-09-28 09:23 UTC, Chocobozzz commented
> I can't see that my changes affect this test, may it be flaky?

I'll relax them!

2022-09-28 11:46 UTC, Chocobozzz requested changes
> To really ensure it works I guess we'd need to setup a WS client and check the message received. I couldn't find more ways in testing it. Any input?

Yes, you can take inspiration of https://github.com/Chocobozzz/PeerTube/blob/develop/server/tests/api/live/live-socket-messages.ts#L72

2022-09-28 11:46 UTC, Chocobozzz commented on server/lib/plugins/plugin-helpers-builder.ts
> +    sendNotification: (userId, notification) => {
Please type parameters

2022-09-28 11:46 UTC, Chocobozzz commented on server/tests/fixtures/peertube-plugin-test-four/main.js
> +      peertubeHelpers.socket.sendNotification(1, {
Most of the type `root` is id `1`, but it may change. It would be better for the tests to send the user id in body

2022-10-10 13:18 UTC, merged