Add ability to disable audit logs
Chocobozzz/PeerTube pull request #6004
Opened 2023-10-12 13:00 UTC by wickloww

## Description

Add ability to disable audit logs in admin panel

## Related issues

Fixes https://github.com/Chocobozzz/PeerTube/issues/2686

## Has this been tested?

- [x] 👍 yes, I added tests to the test suite
- [ ] 💭 no, because this PR is a draft and still needs work
- [ ] 🙅 no, because this PR does not update server code
- [ ] 🙋 no, because I need help 

## Screenshots

![image](https://github.com/Chocobozzz/PeerTube/assets/123956049/000d9e1f-b66b-4329-b684-83cec522a073)

2023-10-18 14:13 UTC, Chocobozzz requested changes

2023-10-18 14:13 UTC, Chocobozzz commented on config/default.yaml
> +  logs:
You already have a log section: https://github.com/Chocobozzz/PeerTube/blob/develop/config/default.yaml#L230

Please also add this block to `production.yaml.example`

2023-10-18 14:13 UTC, Chocobozzz commented on client/src/app/+admin/config/edit-custom-config/edit-advanced-configuration.component.html
> +  <div class="row mt-4"> <!-- cache grid -->
You can remove HTML comments

2023-10-18 14:13 UTC, Chocobozzz commented on client/src/app/+admin/config/edit-custom-config/edit-advanced-configuration.component.html
> +      <div i18n class="inner-form-description">
The description of this block is invalid

2023-10-18 14:13 UTC, Chocobozzz commented on client/src/app/+admin/system/logs/logs.component.html
> +    <div *ngIf="isAuditLog && !isAuditLogsEnabled" i18n>Audit logs disabled.</div>
`isAuditLog` is a function so `isAuditLog()`

Also transform `isAuditLogsEnabled` to a function. `is..` is for functions, if you still want to have a variable then prefer `auditLogsEnabled`. But it's better to have a function to not mix variables/functions if we can avoid

2023-10-18 14:13 UTC, Chocobozzz commented on client/src/app/+admin/system/logs/logs.component.html
> +    <div *ngIf="!loading && logs.length === 0 && isAuditLogsEnabled" i18n>No log.</div>
If audit logs is disabled but you're on the normal logs, you'll never see this message

I suggest to simplify lines 41/43 using an Angular else for example (not easy to use, but will be simpler in the future with the new Angular markup language: https://blog.angular.io/meet-angulars-new-control-flow-a02c6eee7843).

2023-10-18 14:13 UTC, Chocobozzz commented on packages/tests/src/api/server/logs.ts
> +      await waitJobs([ server ])
Just upload one video to test audit logs. Test 403 if disabled, but also the audit log was not filled when it was disabled (so re-enable the feature and check the audit log doesn't contain your upload)

2023-11-02 19:30 UTC, ThisIsMissEm commented
You may not want to actually have this as a feature, as it may violate some of the requirements for the Digital Services Act (e.g., to be able to provide evidence as to what an admin/moderator did and when.

The only case that I could see this being argued for is on a single-user instance, but even then audit logs are useful in case you forget doing something.

2023-11-06 07:18 UTC, Chocobozzz commented
Audit logs would be enabled by default. But the instance is owned by the admin, so we give them the choice as this feature has been requested by some of them :)

2023-11-06 15:38 UTC, ThisIsMissEm commented
> Audit logs would be enabled by default. But the instance is owned by the admin, so we give them the choice as this feature has been requested by some of them :)

Maybe so, but they're still an important feature for trust & safety (and as noted in other issues can be used to implement features for things like actions taken on reports)

It'd be good to know *why* they want to disable the audit logs? What problem are the audit logs creating that could necessitate them needing to be disabled?

2024-02-23 13:37 UTC, Chocobozzz commented
Closing due to inactivity. Does not hesitate to ask for the reopening :)

2024-02-23 13:37 UTC, closed without merging