feat(API): permissive email check in reset & verification
Chocobozzz/PeerTube pull request #6648
Opened 2024-10-01 20:43 UTC by kontrollanten

## Description
In order to not force users to be case sensitive when asking for password reset or resend email verification. When there's multiple emails where the only difference in the local is the capitalized letters, in those cases the users has to be case sensitive.

- [ ] When a user tries to login: fetch all emails in the database case insensitive. If there's only one match, then treat it as the correct email even if they differ in capitalized letters.
- [x] When a user tries to reset password: fetch all emails in the database case insensitive. If there's only one match, then treat it as the correct email even if they differ in capitalized letters.
- [x] When a user tries to get a new verification email: fetch all emails in the database case insensitive. If there's only one match, then treat it as the correct email even if they differ in capitalized letters.

## Related issues
closes #6570

## Has this been tested?

- [x] 👍 yes, I added tests to the test suite
- [ ] 💭 no, because this PR is a draft and still needs work
- [ ] 🙅 no, because this PR does not update server code
- [ ] 🙋 no, because I need help 

## Screenshots

2025-01-14 15:09 UTC, Chocobozzz requested changes
Thanks for the PR! Please add verification email test for user registration too

2025-01-14 15:09 UTC, Chocobozzz commented on packages/tests/src/api/users/oauth.ts
> +      const user = { username: 'User@example.com', password: 'password' }
Please duplicate the test instead of replacing it (you can for example use multiple login in this test)

2025-01-14 15:09 UTC, Chocobozzz commented on packages/tests/src/api/users/oauth.ts
> +    it('Should be able to login with an insensitive email when no similar emails exist', async function () {
Can you also do an offensive test where you test you cannot login if there are multiple email (insensitive cases)

2025-01-14 15:09 UTC, Chocobozzz commented on server/core/lib/auth/oauth-model.ts
> +  } else {
`else if (users.length === 1) {` is cleaner (`users[0]` may not exist)

2025-01-14 15:09 UTC, Chocobozzz commented on server/core/models/user/user.ts
> +  static loadByEmailCaseInsensitive (email: string): Promise<MUserDefault[]> {
I think you can remove `loadByEmail` method

2025-01-14 15:09 UTC, Chocobozzz commented on server/core/models/user/user.ts
>    static loadByUsernameOrEmail (username: string, email?: string): Promise<MUserDefault> {
Remove this method and replace the existing call by `loadByUsernameOrEmailCaseInsensitive`. Starting from now we want to prevent username/email duplicates in the database

2025-01-22 21:12 UTC, kontrollanten commented
@Chocobozzz Your comments are resolved. But now some of the new tests fails since the email exists check is case insensitive.

2025-01-28 13:16 UTC, Chocobozzz commented
Thanks!

2025-01-28 13:16 UTC, merged