Plugin support for sophisticated spam handling
Chocobozzz/PeerTube pull request #6692
Opened 2024-10-25 07:48 UTC by kontrollanten

## Description
Add support for plugins to filter action menus on:
* Admin user list, bulk and single
* Admin comment list, bulk and single
* Admin abuse list, single
* Admin user moderation (available in multiple views)

Add support for `doAction` plugin API. Supported actions:
* Increment/decrement loader
* Admin user list, load data
* Admin video comment list, load data
* Admin user list, load data
* Admin abuse list, load data
* Video watch comment list, load data

Proof of concept with a plugin available at https://framagit.org/kontrollanten/official-plugins/-/merge_requests/new/diffs?merge_request%5Bsource_branch%5D=feat-akismet-mark-as-spam

## Related issues
closes #6264 

## Has this been tested?

- [x] 🙅 no, because this PR does not update server code

## Screenshots
![image](https://github.com/user-attachments/assets/49a9be0b-74f2-49de-88ad-81b4136b71b3)
![image](https://github.com/user-attachments/assets/c9cfa3c2-546f-4782-8d6b-1f6af051b725)
![image](https://github.com/user-attachments/assets/4190a48c-c56c-481e-9365-2b8ee7817880)
![image](https://github.com/user-attachments/assets/3759c392-41a0-4c17-9188-4a7fe85ceb45)
![image](https://github.com/user-attachments/assets/d6358dcc-1ca2-4e3a-93a5-890c7d8b5af3)
![image](https://github.com/user-attachments/assets/94d5b33b-ebd7-4340-9c36-bf9d17f33b2f)
![image](https://github.com/user-attachments/assets/34365ee4-91be-4780-8ec3-da078ca4945f)

2025-01-14 13:23 UTC, Chocobozzz requested changes
Thank you very much for the PR and sorry for the late review.

Can you also update the plugin documentation? https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/plugins/guide.md and https://framagit.org/framasoft/peertube/documentation/-/blob/master/docs/api/plugins.md?ref_type=heads

2025-01-14 13:23 UTC, Chocobozzz commented on client/src/app/core/plugins/plugin.service.ts
> +      logger.warn(`Plugin tried to do unknown action: ${actionName}`)
Action may also crash :)

```
logger.warn(`Cannot run action ${actionName}`, err)
```

2025-01-14 13:23 UTC, Chocobozzz commented on packages/models/src/plugins/client/client-hook.model.ts
> +  'filter:admin-user-list.bulk-actions.create.result': true,
`filter:admin-user-list.bulk-actions.create.result` for consistency (`s` to `user`). Please also do the same with `video-comment` -> `video-comments`

2025-01-14 13:23 UTC, Chocobozzz commented on packages/models/src/plugins/client/client-hook.model.ts
> +export type ClientDoActionCallback = () => Observable<any>
Replace `Observable` by a `Promise` here. We don't want to force to use `Observable`, and we can easily convert a `Promise` to an `Observable` in the client

2025-01-14 13:23 UTC, Chocobozzz commented on client/src/app/+admin/overview/users/user-list/user-list.component.ts
> +    this.pluginService.addAction('admin-user-list:load-data', this.reloadDataInternal.bind(this))
So we don't accidentally break plugin API when we update `reloadDataInternal` parameters below, prefer to create a dedicated callback. For example

```ts
this.pluginService.addAction('admin-user-list:load-data', (options: { ... }) => this.reloadDataInternal({ ... }))
```

2025-01-14 13:23 UTC, Chocobozzz commented on client/src/app/+admin/overview/users/user-list/user-list.component.ts
> +    .pipe(shortCacheObservable())
Is the purpose of `shortCacheObservable` to cache too many calls of `admin-user-list:load-data` in a short period of time)? If yes, prefer to move this to the `addAction` because we don't want the root component to have this side effect, especially since you don't use a cache based on the `getUsers` options.

2025-01-14 13:23 UTC, Chocobozzz commented on client/src/app/+videos/+video-watch/shared/comment/video-comments.component.ts
> +        currentPage: reset === true ? 1 : this.componentPagination.currentPage
I think that if `reset === true` you must do `this.componentPagination.currentPage = 1` or you'll loose pagination in future calls

2025-01-14 13:23 UTC, Chocobozzz commented on client/src/app/shared/shared-moderation/user-moderation-dropdown.component.ts
> +    this.userActions = await this.hooks.wrapObject(userActions, 'admin-users', 'filter:admin-user-moderation.actions.create.result')
The user moderation dropdown can be called in many pages. So I think you can create a `moderation` scope and use `filter:user-moderation.actions.create.result` as hook name

2025-01-14 13:23 UTC, Chocobozzz commented on client/src/app/shared/shared-video-comment/video-comment-list-admin-owner.component.ts
> +      'admin-comments',
If you only want admins to use this hook, then check `this.mode === 'admin'`

2025-01-15 07:30 UTC, Chocobozzz commented on client/src/app/+admin/overview/users/user-list/user-list.component.ts
> +    this.pluginService.addAction('admin-user-list:load-data', this.reloadDataInternal.bind(this))
Oh sorry I didn't see you could not pass params. But is is a `load-data` or a `reload-data` action then?

2025-01-15 07:48 UTC, Chocobozzz commented on client/src/app/+admin/overview/users/user-list/user-list.component.ts
> +    .pipe(shortCacheObservable())
I suggest to remove this cache to avoid side effects, and if it's necessary throttle or debounce the method call

2025-01-15 20:59 UTC, kontrollanten commented on client/src/app/+admin/overview/users/user-list/user-list.component.ts
> +    this.pluginService.addAction('admin-user-list:load-data', this.reloadDataInternal.bind(this))
When a plugin calls the action it will reload the data (reset). In one way `load-data` may be better to keep consistency if we'd like to add parameters to give plugins ability to pass query params to filter the data. On the other hand `reload-data` is more clearly for the plugin developer.

2025-01-16 07:12 UTC, Chocobozzz commented on client/src/app/+admin/overview/users/user-list/user-list.component.ts
> +    this.pluginService.addAction('admin-user-list:load-data', this.reloadDataInternal.bind(this))
I'll let you decide the implementation you want to develop. Both solutions are okay for me :)

2025-01-22 21:15 UTC, kontrollanten commented on client/src/app/+admin/overview/users/user-list/user-list.component.ts
> +    this.pluginService.addAction('admin-user-list:load-data', this.reloadDataInternal.bind(this))
Lets keep load-data to be able to have it flexible.

2025-01-22 21:56 UTC, kontrollanten commented on client/src/app/+admin/overview/users/user-list/user-list.component.ts
> +    .pipe(shortCacheObservable())
The cache was due to multiple API calls made since we had multiple subscribes. I fixed this in the latest commit.

2025-01-22 22:34 UTC, kontrollanten commented
@Chocobozzz All comments fixed. The failing tests seem to be the same as in develop branch.

2025-01-23 07:45 UTC, kontrollanten commented
I did a last (?) update with changing action `admin-user-list:load-data` to `admin-users-list:load-data` and also updated the docs. I tried to update the dedicated API docs but got this error when I referenced to the new file `client-action.model.ts`:

![image](https://github.com/user-attachments/assets/9a63f66e-8b6e-4725-8065-2d02658b0f23)

2025-01-28 13:44 UTC, merged

2025-01-28 13:45 UTC, Chocobozzz commented
Thanks! I added some commits for styling and removed the cache observable because I don't think it worked (we create a new observable everytime the method is called so I'm not sure piping it to a replay factory would work).

If you notice issues with the main branch please don't hesitate to create an issue!